version: "3"
services:

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - 'env.influxdb'
    volumes:
      - ./influxdb:/var/lib/influxdb
    networks:
      - webnet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    depends_on:
      - influxdb
    networks:
      - webnet
    volumes:
      - ./grafana:/var/lib/grafana

networks:
  webnet:
